name: Build and Deploy Criminal Evidence Management System Spring Boot App
on: 
    push: 
        branches: 
            - develop
            - master
jobs: 
    build-deploy: 
        name: Build and Deploy Criminal Evidence Management System App
        runs-on: ubuntu-latest
        steps: 
            - name: checkout code
              uses: actions/checkout@v3
              
              
            - name: Setup JDK 22
              uses: actions/setup-java@v3
              with: 
                  distribution: 'corretto'
                  java-version: 22
                  
            - name: Unit Tests
              run: mvn -B test --file pom.xml
            
            - name: build the application
              run: |
                mvn clean
                mvn -B package --file pom.xml
            