name: Build and Deploy Criminal Evidence Management System Spring Boot App
on: 
    push: 
        branches: 
            - develop
            - master
jobs: 
    build-deploy: 
        name: Build and Deploy Criminal Evidence Management System App
        runs-on: ubuntu-latest
        steps: 
            - name: checkout code
              uses: actions/checkout@v3
              
              
            - name: Setup JDK 22
              uses: actions/setup-java@v3
              with: 
                  distribution: 'corretto'
                  java-version: 22
                  
            - name: Unit Tests
              run: mvn -B test --file pom.xml
            
            - name: build the application
              run: |
                mvn clean
                mvn -B package --file pom.xml
                
            - name: build docker image
              uses: actions/build-push-action@v2
              with: 
                  context: .
                  dockerfile: Dockerfile
                  push: false
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot:$(date-'%Y-%m-%d%H-%M-%S')
                  
            - name: Login to dockerHub
              uses: docker/login-action@v1
              with: 
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
                  
            - name: Push to docker Hub
              uses: actions/build-push-action@v2
              with: 
                  context: .
                  dockerfile: Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot:$(date-'%Y-%m-%d%H-%M-%S')
            